export default function TermsPage() {
  return (
    <main className="flex-1">
      <div className="mx-auto max-w-[760px] px-8 py-18">
        <div className="flex flex-col gap-1.5 border-b border-line-strong pb-7">
          <div className="text-[11px] tracking-[0.2em] text-gold uppercase">
            Legal
          </div>
          <h1 className="font-heading text-[34px] font-semibold">
            Terms of use
          </h1>
        </div>

        <div className="flex flex-col gap-6 pt-8 text-[14.5px] leading-[1.65] text-mut">
          <p>
            DentalBridge is an informational planning tool for
            internationally trained dentists exploring the route to GDC
            registration and UK practice. By using this service you agree to
            the terms below.
          </p>

          <section className="flex flex-col gap-2">
            <h2 className="font-heading text-lg font-semibold text-ink">
              1. Informational purpose only
            </h2>
            <p>
              Roadmaps generated by DentalBridge are drawn from a structured
              knowledge base and narrated with AI assistance. They are a
              planning aid, not professional, legal, immigration, or
              regulatory advice. Always verify requirements against official
              sources — the GDC, UKVI, ORE/OSCE providers, and NHS/employer
              guidance — before making decisions.
            </p>
          </section>

          <section className="flex flex-col gap-2">
            <h2 className="font-heading text-lg font-semibold text-ink">
              2. Content accuracy
            </h2>
            <p>
              Some pathway content is a structural draft pending
              subject-matter-expert review, and is flagged as such in the
              app and any exported PDF. We make reasonable efforts to keep
              information current but cannot guarantee it reflects the
              latest regulatory changes.
            </p>
          </section>

          <section className="flex flex-col gap-2">
            <h2 className="font-heading text-lg font-semibold text-ink">
              3. Your account
            </h2>
            <p>
              You&apos;re responsible for keeping your login credentials
              secure and for the accuracy of the information you submit in
              the questionnaire.
            </p>
          </section>

          <section className="flex flex-col gap-2">
            <h2 className="font-heading text-lg font-semibold text-ink">
              4. Changes
            </h2>
            <p>
              We may update these terms as the product evolves. Continued
              use after a change constitutes acceptance of the revised
              terms.
            </p>
          </section>

          <p className="text-[13px]">
            Questions about these terms? Reach us via the{" "}
            <a href="/contact" className="border-b border-gold text-gold">
              contact page
            </a>
            .
          </p>
        </div>
      </div>
    </main>
  );
}
